name: Global Testing

on:
  pull_request:
    branches:
    - main
jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: pip install pypeg2
    - run: pip install coverage
    - run: pip install PyYAML==5.1
    - run: pip install python-coveralls==2.9.1
    - run: python3 tests.py --x64 --linux --pybase "/opt/hostedtoolcache/Python/3.10.9/x64"
